### PR TITLE
Bump to latest intellij version

### PR DESCRIPTION
**Pull request by ryan-bradford**
# Description:
Updates the plugin to work with the latest IntelliJ version.

# Testing Done:
1. Built + installed in IntelliJ and observed it working.

### CODE REVIEW

**Review by CichyBart — APPROVED** [review]

**Comment by ryan-bradford** [comment]
Great, I've ran a bunch more testing and everything works smoothly.

Whoever has the powers, feel free to merge this change!

**Comment by hankopatrik** [comment]
Hi  @ryan-bradford & @CichyBart . How do you test this, guys? When I'm running ./gradlew buildPlugin I'm getting errors like:
_.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2023.1.3\4e0a4eba55b0959c8406c9be8c38a4937fc99bd1\ideaIC-2023.1.3\lib\app.jar(/com/intellij/lang/xml/XMLLanguage.class)
    class file has wrong version 61.0, should be 55.0_

or
 _The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 2023.1.3 requires sourceCompatibility=17._

I tried switching between java versions, 11 and 17, but is not working. Any tips? Thanks!

**Comment by ryan-bradford** [comment]
@hankopatrik for me, running Java 17 and executing "./gradlew clean build" works from this branch.

I'm on Arch linux, and switch JDKs by running "sudo archlinux-java set java-17-openjdk". After executing this, the build command passes.

If I'm on JDK 11, it fails with a whole slew of errors that look similar to the ones you're experiencing.
`
> Task :compileJava FAILED
/home/bradfordr/Downloads/eclipser/src/main/java/com/kukido/eclipser/EclipserAction.java:3: error: cannot access AnAction
import com.intellij.openapi.actionSystem.AnAction;
                                        ^
  bad class file: /home/bradfordr/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/lib/app.jar(/com/intellij/openapi/actionSystem/AnAction.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/home/bradfordr/Downloads/eclipser/src/main/java/com/kukido/eclipser/EclipserAction.java:4: error: cannot access AnActionEvent
import com.intellij.openapi.actionSystem.AnActionEvent;
                                        ^
  bad class file: /home/bradfordr/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/lib/app.jar(/com/intellij/openapi/actionSystem/AnActionEvent.class)
    class file has wrong version 61.0, should be 55.0`

**Comment by kukido** [comment]
The plugin source code was updated to latest build tools and IntelliJ version. It is available from the plugin repository now.

**Comment by kukido** [comment]
The plugin is available: https://plugins.jetbrains.com/plugin/7153-eclipser/versions/stable/415276

**Pull request closed without merging**
