### PR TITLE
Implement DomSupportEnabled on EclipserFileType

### PR DESCRIPTION
**Pull request by taizel**
Attempt to fix issue #32.

Credit to @krasa for pointing the change that seems to fix the issue. I did a quick test and POM navigation was working again with this change.

### CODE REVIEW

**Comment by kukido** [comment]
Let me check the build and if it works, I will merge and publish the new version of the plugin.

**Comment by rtconner** [comment]
Would this fix it so I could install this plugin on the latest version of IntelliJ? I cannot install this plugin it does not show in the list when I search for plugins.

I could really use these features a lot.

**Comment by taizel** [comment]
@kukido any news on that? Is there anything I can do to help with the release?

**Comment by kukido** [comment]
I cherry-picked the changes, and published the plugin. Thank you for contributing!
https://plugins.jetbrains.com/plugin/7153-eclipser/versions/stable/92473

**Pull request closed without merging**
